### Author:

    HOANG MINH KHIEM - 16520588
    TRAN ANH TUAN - 16521386

### Overview: 
In this assignment, you will need to apply data analytics, using the tools introduced during the labs. You are required to study the SEEK job market data and analyze. The assignment consists of 3 parts. In the first part, you will need to understand data characteristics using data preparation and preprocessing techniques. In the second part, you will perform various data analysis techniques, including exploratory, statistical, and predictive ones. In the third part, you will need to evaluate your findings and determine appropriate future actions.

# Part 1 - Data Preparation and Preprocessing

    ● The primary dataset that we would like to use is the job market dataset which is provided in CSV format (data.csv).
    ● Perform data preparation and preprocessing for your analysis.
    ● Submit your Jupyter notebook in your Github repository

In [40]:
import pandas as pd
import numpy as np

df = pd.read_csv('data.csv')
df.head()

D:\Apps\Ananconda3.7\Anaconda3.7\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (0,4,5,6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Id,Title,Company,Date,Location,Area,Classification,SubClassification,Requirement,FullDescription,LowestSalary,HighestSalary,JobType
0,37404348,Casual Stock Replenisher,Aldi Stores,2018-10-07T00:00:00.000Z,Sydney,North West & Hills District,Retail & Consumer Products,Retail Assistants,Our Casual Stock Replenishers pride themselves...,NaN,0,30,NaN
1,37404337,Casual Stock Replenisher,Aldi Stores,2018-10-07T00:00:00.000Z,Richmond & Hawkesbury,NaN,Retail & Consumer Products,Retail Assistants,Our Casual Stock Replenishers pride themselves...,NaN,0,30,NaN
2,37404356,RETAIL SALES SUPERSTARS and STYLISTS Wanted - ...,LB Creative Pty Ltd,2018-10-07T00:00:00.000Z,Brisbane,CBD & Inner Suburbs,Retail & Consumer Products,Retail Assistants,BRAND NEW FLAGSHIP STORE OPENING - SUNSHINE PLAZA,NaN,0,30,NaN
3,37404330,Team member - Belrose,Anaconda Group Pty Ltd,2018-10-07T00:00:00.000Z,Gosford & Central Coast,NaN,Retail & Consumer Products,Retail Assistants,Bring it on - do you love the great outdoors a...,NaN,0,30,NaN
4,37404308,"Business Banking Contact Centre Specialist, Ni...",Commonwealth Bank - Business & Private Banking,2018-10-07T00:00:00.000Z,Sydney,Ryde & Macquarie Park,Call Centre & Customer Service,Sales - Inbound,"We are seeking highly articulate, enthusiastic...",NaN,0,30,NaN

### 1) Describe the dataset.
    ● Describe the steps you used for data preparation and preprocessing

In [41]:
df.columns

Index(['Id', 'Title', 'Company', 'Date', 'Location', 'Area', 'Classification',
       'SubClassification', 'Requirement', 'FullDescription', 'LowestSalary',
       'HighestSalary', 'JobType'],
      dtype='object')

    ● Dataset size of each variation:

In [42]:
df.info(0)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 318477 entries, 0 to 318476
Data columns (total 13 columns):
Id                   318477 non-null object
Title                318477 non-null object
Company              306473 non-null object
Date                 318477 non-null object
Location             197229 non-null object
Area                 122658 non-null object
Classification       197229 non-null object
SubClassification    197229 non-null object
Requirement          318470 non-null object
FullDescription      302302 non-null object
LowestSalary         318477 non-null int64
HighestSalary        318477 non-null int64
JobType              302379 non-null object
dtypes: int64(2), object(11)
memory usage: 31.6+ MB

    ● Dataset structure/format:

In [43]:
df.dtypes

Id                   object
Title                object
Company              object
Date                 object
Location             object
Area                 object
Classification       object
SubClassification    object
Requirement          object
FullDescription      object
LowestSalary          int64
HighestSalary         int64
JobType              object
dtype: object

    ● Attributes/features of review data that I'm going to use (Location, Classification, SubClassification):

In [44]:
df['Location'].describe()

count     197229
unique        65
top       Sydney
freq       60765
Name: Location, dtype: object

In [45]:
df['Classification'].describe()

count                                     197229
unique                                        30
top       Information & Communication Technology
freq                                       22796
Name: Classification, dtype: object

In [46]:
df['SubClassification'].describe()

count     197229
unique       338
top        Other
freq       11349
Name: SubClassification, dtype: object

    ● Attributes/features of product data that I'm going to use (LowestSalary, HighestSalary):

In [47]:
df['LowestSalary'].describe()

count    318477.000000
mean         65.813544
std          51.063125
min           0.000000
25%          30.000000
50%          60.000000
75%         100.000000
max         200.000000
Name: LowestSalary, dtype: float64

In [48]:
df['HighestSalary'].describe()

count    318477.000000
mean        114.432342
std         177.594941
min          30.000000
25%          40.000000
50%          70.000000
75%         120.000000
max         999.000000
Name: HighestSalary, dtype: float64

    ● Which parts of the dataset will you use or all of them?
        - In this assigment, we will use all the given columns except "Id", "Area", "Full Description".


### 2) Describe the steps you used for data preparation and preprocessing.

    ● How do you load the data using Pandas?
        - First, I import pandas.
        - Then, I use "df = pd.read_csv('data.cv') command to load the csv file to the Data frame.
        - To obsever the data, I use "df.head()" to display top data.
    
    
    ● How do you normalize the data?
        - I will use Min-Max normalization to normalize 3 columns (LowestSalary, HighestSalary).

In [49]:
new_df = df.copy()

# Min-Max normalization for Lowest Salary:
new_df['LowestSalary'] = new_df['LowestSalary'] / new_df['LowestSalary'].max() 

# Min-Max normalization for Highest Salary:
new_df['HighestSalary'] = new_df['HighestSalary'] / new_df['HighestSalary'].max()

new_df.head()

,Id,Title,Company,Date,Location,Area,Classification,SubClassification,Requirement,FullDescription,LowestSalary,HighestSalary,JobType
0,37404348,Casual Stock Replenisher,Aldi Stores,2018-10-07T00:00:00.000Z,Sydney,North West & Hills District,Retail & Consumer Products,Retail Assistants,Our Casual Stock Replenishers pride themselves...,NaN,0.0,0.03003,NaN
1,37404337,Casual Stock Replenisher,Aldi Stores,2018-10-07T00:00:00.000Z,Richmond & Hawkesbury,NaN,Retail & Consumer Products,Retail Assistants,Our Casual Stock Replenishers pride themselves...,NaN,0.0,0.03003,NaN
2,37404356,RETAIL SALES SUPERSTARS and STYLISTS Wanted - ...,LB Creative Pty Ltd,2018-10-07T00:00:00.000Z,Brisbane,CBD & Inner Suburbs,Retail & Consumer Products,Retail Assistants,BRAND NEW FLAGSHIP STORE OPENING - SUNSHINE PLAZA,NaN,0.0,0.03003,NaN
3,37404330,Team member - Belrose,Anaconda Group Pty Ltd,2018-10-07T00:00:00.000Z,Gosford & Central Coast,NaN,Retail & Consumer Products,Retail Assistants,Bring it on - do you love the great outdoors a...,NaN,0.0,0.03003,NaN
4,37404308,"Business Banking Contact Centre Specialist, Ni...",Commonwealth Bank - Business & Private Banking,2018-10-07T00:00:00.000Z,Sydney,Ryde & Macquarie Park,Call Centre & Customer Service,Sales - Inbound,"We are seeking highly articulate, enthusiastic...",NaN,0.0,0.03003,NaN

    ● How do you clean the data?
        - First, I will drop the unecessary columns, in this case are Id, Company, Area, FullDescription.

In [50]:
new_df = new_df.drop(['Id', 'Area', 'FullDescription'], axis =1)

new_df.head()

,Title,Company,Date,Location,Classification,SubClassification,Requirement,LowestSalary,HighestSalary,JobType
0,Casual Stock Replenisher,Aldi Stores,2018-10-07T00:00:00.000Z,Sydney,Retail & Consumer Products,Retail Assistants,Our Casual Stock Replenishers pride themselves...,0.0,0.03003,NaN
1,Casual Stock Replenisher,Aldi Stores,2018-10-07T00:00:00.000Z,Richmond & Hawkesbury,Retail & Consumer Products,Retail Assistants,Our Casual Stock Replenishers pride themselves...,0.0,0.03003,NaN
2,RETAIL SALES SUPERSTARS and STYLISTS Wanted - ...,LB Creative Pty Ltd,2018-10-07T00:00:00.000Z,Brisbane,Retail & Consumer Products,Retail Assistants,BRAND NEW FLAGSHIP STORE OPENING - SUNSHINE PLAZA,0.0,0.03003,NaN
3,Team member - Belrose,Anaconda Group Pty Ltd,2018-10-07T00:00:00.000Z,Gosford & Central Coast,Retail & Consumer Products,Retail Assistants,Bring it on - do you love the great outdoors a...,0.0,0.03003,NaN
4,"Business Banking Contact Centre Specialist, Ni...",Commonwealth Bank - Business & Private Banking,2018-10-07T00:00:00.000Z,Sydney,Call Centre & Customer Service,Sales - Inbound,"We are seeking highly articulate, enthusiastic...",0.0,0.03003,NaN

        - Then, I will replace "JobType" missing value by "No detail" value:

In [51]:
new_df['JobType'] = new_df['JobType'].fillna('No Detail')

new_df.head()

,Title,Company,Date,Location,Classification,SubClassification,Requirement,LowestSalary,HighestSalary,JobType
0,Casual Stock Replenisher,Aldi Stores,2018-10-07T00:00:00.000Z,Sydney,Retail & Consumer Products,Retail Assistants,Our Casual Stock Replenishers pride themselves...,0.0,0.03003,No Detail
1,Casual Stock Replenisher,Aldi Stores,2018-10-07T00:00:00.000Z,Richmond & Hawkesbury,Retail & Consumer Products,Retail Assistants,Our Casual Stock Replenishers pride themselves...,0.0,0.03003,No Detail
2,RETAIL SALES SUPERSTARS and STYLISTS Wanted - ...,LB Creative Pty Ltd,2018-10-07T00:00:00.000Z,Brisbane,Retail & Consumer Products,Retail Assistants,BRAND NEW FLAGSHIP STORE OPENING - SUNSHINE PLAZA,0.0,0.03003,No Detail
3,Team member - Belrose,Anaconda Group Pty Ltd,2018-10-07T00:00:00.000Z,Gosford & Central Coast,Retail & Consumer Products,Retail Assistants,Bring it on - do you love the great outdoors a...,0.0,0.03003,No Detail
4,"Business Banking Contact Centre Specialist, Ni...",Commonwealth Bank - Business & Private Banking,2018-10-07T00:00:00.000Z,Sydney,Call Centre & Customer Service,Sales - Inbound,"We are seeking highly articulate, enthusiastic...",0.0,0.03003,No Detail

        - Lastly, for the rest missing values, we just remove the entire row:

In [52]:
new_df.dropna()

,Title,Company,Date,Location,Classification,SubClassification,Requirement,LowestSalary,HighestSalary,JobType
0,Casual Stock Replenisher,Aldi Stores,2018-10-07T00:00:00.000Z,Sydney,Retail & Consumer Products,Retail Assistants,Our Casual Stock Replenishers pride themselves...,0.0,0.03003,No Detail
1,Casual Stock Replenisher,Aldi Stores,2018-10-07T00:00:00.000Z,Richmond & Hawkesbury,Retail & Consumer Products,Retail Assistants,Our Casual Stock Replenishers pride themselves...,0.0,0.03003,No Detail
2,RETAIL SALES SUPERSTARS and STYLISTS Wanted - ...,LB Creative Pty Ltd,2018-10-07T00:00:00.000Z,Brisbane,Retail & Consumer Products,Retail Assistants,BRAND NEW FLAGSHIP STORE OPENING - SUNSHINE PLAZA,0.0,0.03003,No Detail
3,Team member - Belrose,Anaconda Group Pty Ltd,2018-10-07T00:00:00.000Z,Gosford & Central Coast,Retail & Consumer Products,Retail Assistants,Bring it on - do you love the great outdoors a...,0.0,0.03003,No Detail
4,"Business Banking Contact Centre Specialist, Ni...",Commonwealth Bank - Business & Private Banking,2018-10-07T00:00:00.000Z,Sydney,Call Centre & Customer Service,Sales - Inbound,"We are seeking highly articulate, enthusiastic...",0.0,0.03003,No Detail
5,"Business Banking Contact Centre Specialist, Ni...",Commonwealth Bank - Business & Private Banking,2018-10-07T00:00:00.000Z,Sydney,Call Centre & Customer Service,Customer Service - Call Centre,"We are seeking highly articulate, enthusiastic...",0.0,0.03003,No Detail
6,Casual Café All-rounder in Semaphore,Jora Local,2018-10-07T00:00:00.000Z,Adelaide,Hospitality & Tourism,Waiting Staff,A cafe/restaurant in Semaphore is seeking a ca...,0.0,0.03003,No Detail
7,Casual Café All-rounder in Woolloongabba,Jora Local,2018-10-07T00:00:00.000Z,Brisbane,Hospitality & Tourism,Waiting Staff,A cafe in Woolloongabba is seeking a casual Ca...,0.0,0.03003,No Detail
8,Telemarketer,Reventon Investments,2018-10-07T00:00:00.000Z,Melbourne,Call Centre & Customer Service,Sales - Outbound,Market leading investment & financial services...,0.0,0.03003,No Detail
9,Casual Dish Hand in Brighton,Jora Local,2018-10-07T00:00:00.000Z,Melbourne,Hospitality & Tourism,Kitchen & Sandwich Hands,A restaurant in Brighton is seeking a casual D...,0.0,0.03003,No Detail
10,Sales and Service Banking Consultant,Hays Talent Solutions,2018-10-07T00:00:00.000Z,Adelaide,Banking & Financial Services,Banking - Retail/Branch,We currently have an exciting part-time opport...,0.0,0.03003,No Detail
12,Functions Supervisor - Perth Zoo,Mustard Catering,2018-10-07T00:00:00.000Z,Perth,Hospitality & Tourism,Bar & Beverage Staff,Casual Food and Beverage Supervisor,0.0,0.03003,No Detail
13,BPV_Utility All Rounders_Casual,ISS Facility Services,2018-10-07T00:00:00.000Z,Mackay & Coalfields,Hospitality & Tourism,Housekeeping,An exciting opportunity exists for Casual DIDO...,0.0,0.03003,No Detail
14,Casual Cleaner in Kew,Jora Local,2018-10-07T00:00:00.000Z,Melbourne,Hospitality & Tourism,Housekeeping,A restaurant in Kew is seeking a casual Cleane...,0.0,0.03003,No Detail
16,Sales and Service Banking Consultant,Hays Talent Solutions,2018-10-07T00:00:00.000Z,Adelaide,Retail & Consumer Products,Retail Assistants,We currently have an exciting part-time opport...,0.0,0.03003,No Detail
17,Maintenance Assistant Part-Time,Costco Wholesale,2018-10-07T00:00:00.000Z,Melbourne,Retail & Consumer Products,Other,Provides janitorial services and general maint...,0.0,0.03003,No Detail
18,Telstra Retail Sales & Service Consultant - Ca...,TLS Airport West,2018-10-07T00:00:00.000Z,Melbourne,Retail & Consumer Products,Retail Assistants,A great opportunity to join the retail team at...,0.0,0.03003,No Detail
19,Assembler,Zoom Recruitment & Training,2018-10-07T00:00:00.000Z,Sydney,"Manufacturing, Transport & Logistics",Assembly & Process Work,"Our Client, located in Sydney West, has roles ...",0.0,0.03003,No Detail
20,Procurement Officer,Perspective Recruitment,2018-10-07T00:00:00.000Z,Melbourne,"Manufacturing, Transport & Logistics","Purchasing, Procurement & Inventory",The role would be ideal for one that has a nat...,0.0,0.03003,No Detail
21,Casual Barista in Murarrie,Jora Local,2018-10-07T00:00:00.000Z,Brisbane,Hospitality & Tourism,Bar & Beverage Staff,A cafe in Murarrie is seeking a casual Barista...,0.0,0.03003,No Detail
22,Sales and Service Banking Consultant,Hays Talent Solutions,2018-10-07T00:00:00.000Z,Adelaide,Banking & Financial Services,Banking - Retail/Branch,We currently have an exciting full time opport...,0.0,0.03003,No Detail
23,Casual Barista in Richmond,Jora Local,2018-10-07T00:00:00.000Z,Melbourne,Hospitality & Tourism,Bar & Beverage Staff,A cafe in Richmond is seeking a casual Barista...,0.0,0.03003,No Detail
24,Sales and Service Banking Consultant,Hays Talent Solutions,2018-10-07T00:00:00.000Z,Adelaide,Sales,Sales Representatives/Consultants,We currently have an exciting part-time opport...,0.0,0.03003,No Detail
25,Casual Cook in Palm Beach,Jora Local,2018-10-07T00:00:00.000Z,Gold Coast,Hospitality & Tourism,Chefs/Cooks,A cafe/restaurant in Palm Beach is seeking a c...,0.0,0.03003,No Detail
26,Clinical Document Processing and Quality Assur...,West Moreton Hospital and Health Service,2018-10-07T00:00:00.000Z,Brisbane,Administration & Office Support,Records Management & Document Control,administrative and systems support in relation...,0.0,0.03003,No Detail
27,Investment Accountant - NAB Asset Servicing,National Australia Bank,2018-10-07T00:00:00.000Z,Sydney,Banking & Financial Services,Analysis & Reporting,Entry level opportunity in Investment Accounti...,0.0,0.03003,No Detail
28,Casual Cook in Melbourne,Jora Local,2018-10-07T00:00:00.000Z,Melbourne,Hospitality & Tourism,Chefs/Cooks,A business in Melbourne is seeking a casual Co...,0.0,0.03003,No Detail
29,Office Administrator - 4 days per week,Accountancy Connect,2018-10-07T00:00:00.000Z,Melbourne,Administration & Office Support,Office Management,Wonderful role based in Cheltenham. Four days ...,0.0,0.03003,No Detail
30,Sales and Service Banking Consultant,Hays Talent Solutions,2018-10-07T00:00:00.000Z,Adelaide,Sales,Sales Representatives/Consultants,We currently have an exciting full time opport...,0.0,0.03003,No Detail
31,Mechanical Minded General Hand - Ingleburn,Zoom Recruitment & Training,2018-10-07T00:00:00.000Z,Sydney,"Manufacturing, Transport & Logistics","Warehousing, Storage & Distribution",We are currently seeking a General Hand to joi...,0.0,0.03003,No Detail
...,...,...,...,...,...,...,...,...,...,...
197199,Speech Pathologist,Access Your Supports,2018-11-29T00:00:00.000Z,South West Coast VIC,Healthcare & Medical,Speech Therapy,We are seeking an experienced Speech Therapist...,1.0,1.00000,Full Time
197200,Senior Data Engineer - GCP (Google Cloud) - C...,TRS - IT & Communications,2018-11-29T00:00:00.000Z,Melbourne,Information & Communication Technology,Consultants,Senior Data Engineer - GCP - Contract - Sydney...,1.0,1.00000,Contract/Temp
197201,Project Manager | Well Established Mid-Tier He...,Quinton Anthony P/L,2018-11-29T00:00:00.000Z,Sydney,Construction,Project Management,Exciting opportunity to deliver a landmark pro...,1.0,1.00000,Full Time
197202,High Rise Project Manager,Hays Construction,2018-11-29T00:00:00.000Z,Gold Coast,Construction,Project Management,High rise Project Manager required for central...,1.0,1.00000,Full Time
197203,Chief Financial Officer (CFO),Alex Kaar,2018-11-29T00:00:00.000Z,Melbourne,Accounting,Financial Managers & Controllers,An exciting opportunity has arisen for an expe...,1.0,1.00000,No Detail
197204,AWS IoT Data Engineer - Energy Sharing,TRS - IT & Communications,2018-11-29T00:00:00.000Z,Sydney,Information & Communication Technology,Consultants,Senior Data Engineer required to build a >1m d...,1.0,1.00000,Contract/Temp
197205,"Design Manager | Mid Tier Builder | Strong, Es...",Quinton Anthony P/L,2018-11-29T00:00:00.000Z,Sydney,Construction,Project Management,This well known main contractor is in search o...,1.0,1.00000,Full Time
197206,Medical Oncologist,Global Medics Australia,2018-11-29T00:00:00.000Z,Darwin,Healthcare & Medical,Medical Specialists,We are seeking an additional Oncologist to joi...,1.0,1.00000,Full Time
197207,Staff Specialist - Rehabilitation,Global Medics Australia,2018-11-29T00:00:00.000Z,Darwin,Healthcare & Medical,Medical Specialists,We are currently working with the new hospital...,1.0,1.00000,Full Time
197208,Multiple TSPV Opportunities – CANBERRA LOCATION,Oakton Contracting & Recruitment Pty Ltd,2018-11-29T00:00:00.000Z,ACT,Information & Communication Technology,Consultants,Multiple job opportunities in Canberra locatio...,1.0,1.00000,Contract/Temp
197209,Senior Project Director | Client Side,Design & Build,2018-11-29T00:00:00.000Z,Sydney,Construction,Project Management,Senior Project Director with a strong industry...,1.0,1.00000,Full Time
197210,Haematologist,Global Medics Australia,2018-11-29T00:00:00.000Z,Dubbo & Central NSW,Healthcare & Medical,Medical Specialists,We are currently arranging interviews for suit...,1.0,1.00000,Full Time
197211,Retail Design Manager,Woolworth Liquor Group,2018-11-29T00:00:00.000Z,Sydney,Design & Architecture,Interior Design,The Design Manager for EDG is responsible for ...,1.0,1.00000,Full Time
197212,Staff Specialist - Palliative Care,Global Medics Australia,2018-11-29T00:00:00.000Z,Dubbo & Central NSW,Healthcare & Medical,Medical Specialists,We are currently assisting a hospital in regio...,1.0,1.00000,Full Time
197213,Construction & Major Projects - Commercial Man...,Sigma Executive,2018-11-29T00:00:00.000Z,Sydney,Legal,Construction Law,Join one of the world's leading infrastructure...,1.0,1.00000,Full Time
197214,Medical Officer,Coal Services Pty Ltd,2018-11-29T00:00:00.000Z,Melbourne,Healthcare & Medical,General Practitioners,Coal Services Health are looking for a Medical...,1.0,1.00000,Full Time
197215,Child and Adolescent Psychiatrist,Kelly Government Solutions,2018-11-29T00:00:00.000Z,"Newcastle, Maitland & Hunter",Healthcare & Medical,"Psychology, Counselling & Social Work",Kelly Services is seeking to engage with a qua...,1.0,1.00000,Contract/Temp
197216,Head of Merchandise Planning,MyHouse,2018-11-29T00:00:00.000Z,Sydney,Retail & Consumer Products,Planning,MyHouse is seeking an experienced Head of Merc...,1.0,1.00000,Full Time
197217,IT Project/ Program Manager - Banking,Illuminate Search & Consulting,2018-11-29T00:00:00.000Z,Sydney,Information & Communication Technology,Programme & Project Management,Ability to deliver a wide federated model,1.0,1.00000,Contract/Temp
197218,IT Test Analyst OR Senior IT Test Analyst,Paxus,2018-11-29T00:00:00.000Z,Sydney,Information & Communication Technology,Testing & Quality Assurance,Great opportunity for a IT Test Analyst/Senio...,1.0,1.00000,Contract/Temp
197219,Medical Officer,Coal Services Pty Ltd,2018-11-29T00:00:00.000Z,Brisbane,Healthcare & Medical,General Practitioners,Coal Services Health are looking for a Medical...,1.0,1.00000,Full Time
197220,Medical Officer,Coal Services Pty Ltd,2018-11-29T00:00:00.000Z,Blue Mountains & Central West,Healthcare & Medical,General Practitioners,Coal Services Health are looking for a Medical...,1.0,1.00000,Full Time
197221,General Practitioner - No Restrictions,City Medical Practice - Burnie,2018-11-29T00:00:00.000Z,Devonport & North West,Healthcare & Medical,General Practitioners,Full Time General Practitioner with no restric...,1.0,1.00000,Full Time
197222,"Contracts Manager - Commercial Lead Required, ...",Quinton Anthony P/L,2018-11-29T00:00:00.000Z,Sydney,Construction,Contracts Management,National $2 billion builder seeking Contracts ...,1.0,1.00000,Full Time
197223,Design Manager | Mid Tier Construction | Newca...,Quinton Anthony P/L,2018-11-29T00:00:00.000Z,"Newcastle, Maitland & Hunter",Construction,Project Management,This well known main contractor is in search o...,1.0,1.00000,Full Time
197224,Environmental Officer- Contaminated Land,Evolve Scientific Recruitment,2018-11-29T00:00:00.000Z,Melbourne,Science & Technology,Food Technology & Safety,Environmental Officer- Contaminated Land | 3-4...,1.0,1.00000,Full Time
197225,Construction Manager Required - Commercial & A...,Constructive Recruitment Pty Ltd,2018-11-29T00:00:00.000Z,Melbourne,Construction,Project Management,Career defining role with buoyant commercial/a...,1.0,1.00000,Full Time
197226,ENT Surgeon,Healthcare Professionals Group,2018-11-29T00:00:00.000Z,"Newcastle, Maitland & Hunter",Healthcare & Medical,Medical Specialists,Responsible for providing surgical procedures ...,1.0,1.00000,Full Time
197227,Orthopaedic Surgeon,Healthcare Professionals Group,2018-11-29T00:00:00.000Z,Port Macquarie & Mid North Coast,Healthcare & Medical,Medical Specialists,Provide your expertise as an Orthopaedic Surge...,1.0,1.00000,Full Time
197228,VMWare Engineer,HEADWAY INFORMATION SERVICES PTY LTD,2018-11-29T00:00:00.000Z,Brisbane,Information & Communication Technology,Networks & Systems Administration,VMware Engineer needed for a VmWare Migration ...,1.0,1.00000,No Detail

### 3) What is your hypothesis (expectation) about the analysis outcome?
        - From given data, I expect that I can find the attributes/features of the job market such as hottest jobs in the market, which jobs have the highest income, what are the requirement of the companies as well as the jobs, etc.
<br><br><br>
        
<i>                                                     Author:
<br>                                              Hoang Minh Khiem
<br>                                                Tran Anh Tuan
    
                                                     ~ END PART 1 ~